### ISSUE TITLE
Do interaction design tests

### ISSUE THREAD

**Issue by beefoo** [beefoo/lclabs-jfp24#14]
Create a simple web demo that tests our intended user interactions (drag, drop, resize, rotate, etc). This library looks promising:

https://interactjs.io/

**Comment by shaunakh24** [comment]
- [ ] HTML/CSS framing (Aisaiah)
- [ ] JavaScript testing (Ilayda)
- [ ] research pre-existing interactive collage web tools (Shauna-Kay)
